### ISSUE TITLE
Registration and interpolation to-do's

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#12]
To-do list not covered in #9:

***Registration***
- [x] Tests of registration.py
- [x] Doctests of registration.py
- [x] Review documentation of registration.py
- [x] Add sample generators to make examples of registration.py
- [x] Examples of registration.py

***Interpolation***
- [x] Write documentation of grid_interpolation.py
- [x] Review documentation of grid_interpolation.py
- [x] Tests of interpolation
- [x] Examples  of interpolation
- [x] Inherit from ABC

***Extrapolation***
- [x] Consider more appropriate names for the extrapolation types
- [x] Think how to unify the extrapolation in the `evaluate` methods of `FDataBasis`and `FDataGrid`
- [x] Decide if the default extrapolation of each type of basis should be a class attribute or an attribute of the instance
