### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pablomm** [GAA-UAM/scikit-fda#131]
I open this issue to unify all pending tasks (in my opinion) with respect to documentation.

- [ ] Write readme
- [ ] Write index page in _readthedocs_, linking to the different modules and to the github repository
- [ ] Provide a project description in [pypi](https://pypi.org/project/scikit-fda/)
- [ ] Make missing examples listed in #117 
- [ ] Fix pdf documentation (#70)
- [ ] Show documentation of methods (#91)
- [ ] Make explicit imports in doctests
- [ ] Remove ``__author__`` and ``__email__`` variables in modules
- [ ] Update ``skfda/__init__.py`` docstring, shown when doing ``import skfda; help(skfda)``
- [ ] Write docstring of top level modules (e.g. ``help(skfda.preprocessing)``)
- [ ] Integrate PEP 257 checker (?)
